featureSelector:
  - RemoveAttribute:
    - name
ruleExtractor:
    FPGrowth:
      support:
        minimum: 0.1
        maximum: 1.0
        step: 0.01
      metric:
        name: confidence
        minimum: 0.1
      numberOfRulesToFind: -1
repository: asd
imports: asd
output: xp